# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-28 23:43
from __future__ import unicode_literals

import customer.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='artist_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('TSHIRT DESIGNER', 'tshirt_designer'), ('HOMEPRENEUR', 'homepreneur')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_designer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='unique_share_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_photo',
            field=models.ImageField(blank=True, default='uploads/user_dummy.jpg', null=True, upload_to=customer.models.get_user_image_path),
        ),
    ]
