# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customeraddress_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='mobile',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='name',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
