# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-31 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20170329_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
