# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customeremailverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_designer',
        ),
    ]
