# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-23 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customer_is_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('amount_type', models.CharField(choices=[('PROMOTIONAL', 'PROMOTIONAL'), ('CASH', 'CASH')], max_length=60)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('particular', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('ADVERTISER', 'ADVERTISER'), ('AB', 'AB'), ('REFERRAL', 'REFERRAL')], max_length=150)),
                ('amount', models.IntegerField(default=0)),
                ('amount_in', models.CharField(choices=[('FLAT', 'FLAT'), ('PERCENTAGE', 'PERCENTAGE')], max_length=150)),
                ('maximum_amount', models.IntegerField(default=0)),
                ('total_applicability', models.IntegerField(default=0)),
                ('each_user_applicability', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('active_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.CharField(choices=[('SIGNUP', 'SIGNUP'), ('ORDER', 'ORDER')], max_length=150)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('redeem_amount', models.IntegerField(default=0)),
                ('redeem_amount_in', models.CharField(choices=[('FLAT', 'FLAT'), ('PERCENTAGE', 'PERCENTAGE')], max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='unique_share_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='d',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='share_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Coupon'),
        ),
        migrations.AddField(
            model_name='abmoney',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Campaign'),
        ),
        migrations.AddField(
            model_name='abmoney',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
