# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-23 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20170923_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='abmoney',
            name='closing_cash_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abmoney',
            name='closing_promotional_money',
            field=models.IntegerField(default=0),
        ),
    ]
