# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-23 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20170923_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='abmoney',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 23, 16, 21, 19, 671431)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abmoney',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 23, 16, 21, 34, 615076)),
            preserve_default=False,
        ),
    ]
