# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-25 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20170925_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount_to_owner',
            field=models.IntegerField(default=0),
        ),
    ]
