# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-10 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_remove_campaign_amount_to_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeremailverify',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 10, 11, 1, 15, 11, 37618)),
            preserve_default=False,
        ),
    ]
