# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-25 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customeremailverify_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_type',
        ),
    ]
