# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-01 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_coupon_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='promotional_money_expiry',
            field=models.IntegerField(default=30),
        ),
    ]
