# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-04 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_campaign_promotional_money_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='redeem_amount_type',
            field=models.CharField(choices=[('PROMOTIONAL', 'PROMOTIONAL'), ('TRANSACTIONAL', 'TRANSACTIONAL')], default='PROMOTIONAL', max_length=150),
            preserve_default=False,
        ),
    ]
