# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-16 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20171126_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='d',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
