# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20160806_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('product.product',),
        ),
    ]
