# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_grocery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grocery',
        ),
        migrations.CreateModel(
            name='Grocery Category',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('product.category',),
        ),
        migrations.CreateModel(
            name='Grocery Products',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('product.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='is_feature_product',
            field=models.BooleanField(default=False),
        ),
    ]
