# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productimage_display_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='display_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
