# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20170105_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_customization_available',
            field=models.BooleanField(default=False),
        ),
    ]
