# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_is_customization_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVarient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient_type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
                ('width', models.IntegerField(default=1)),
                ('length', models.IntegerField(default=1)),
                ('is_ready_to_ship', models.BooleanField(default=False)),
                ('fast_delivery_avelable', models.BooleanField(default=False)),
                ('gift_wrap_avelable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVarientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('key', models.ManyToManyField(to='product.CategoryVarient')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='size_chart_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_details',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('DESIGNER', 'designer'), ('NORMAL', 'normal'), ('USERQUERY', 'userquery')], default=('NORMAL', 'normal'), max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='ProductVarient',
        ),
        migrations.AddField(
            model_name='productvarientlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='categoryvarient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
    ]
