# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-29 05:17
from __future__ import unicode_literals

from django.db import migrations
from product.models import Category, CategoryVarient


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productartist'),
    ]

    def product_data_sanity(a,b):
        tee = Category.objects.create(
            parent=None, name='tshirt', active=True, publisher='anuj')
        old = Category.objects.get(unique_name='Mens-Topwear-T-Shirts')
        sub = Category.objects.filter(parent=old)
        for i in sub:
            i.parent = tee
            i.save()

        for i in CategoryVarient.objects.filter(category=old):
            i.category = tee
            i.save()

    operations = [
        migrations.RunPython(product_data_sanity),
    ]
