# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-09 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20170829_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='productartist',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductArtist',
        ),
    ]
