# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-15 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20170729_2121'),
        ('product', '0021_auto_20170909_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarientlist',
            name='sellers',
            field=models.ManyToManyField(to='seller.Seller'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_chart_url',
            field=models.ImageField(blank=True, default='uploads/blogimages/dummy.jpg', null=True, upload_to=product.models.category_size_chart),
        ),
    ]
