# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20170916_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarientlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
