# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20171102_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=450)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_combo_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comboproducts',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
