# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-03 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20171126_1541'),
        ('product', '0025_productimage_category_varient'),
    ]

    operations = [
    ]
