# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20171126_1541'),
        ('product', '0025_auto_20171126_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rule', models.CharField(max_length=200)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Coupon')),
            ],
        ),
    ]
