# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Coupon'),
        ),
    ]
