# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-03 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20171203_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
