# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-04 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_productoffer_active'),
        ('product', '0026_merge'),
    ]

    operations = [
    ]
