# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20171219_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='rule',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
