# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20171219_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarientlist',
            name='product_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductImage'),
        ),
    ]
