# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-04 16:22
from __future__ import unicode_literals

from django.db import migrations
from product.models import CategoryVarient, Category


def category_creator(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    category = Category.objects.filter(slug='croptop')
    if category:
        category = category[0]
    else:
        category = Category.objects.create(name='croptop',
                                           description='croptop for girls',
                                           active=True,)
        print 'Update Size Chart URL'
    size = ['XS', 'S', 'M', 'L', 'XL', 'XXL']
    for s in size:
        CategoryVarient.objects.create(
            category=category, varient_type='SIZE', value=s)
    color = ['BLUE', 'YELLOW', 'DARK BLUE', 'BLACK', 'MAROON',
             'ORANGE', 'WHITE', 'DARK GREY', 'RED', 'LIGHT GREY']
    for s in color:
        CategoryVarient.objects.create(
            category=category, varient_type='COLOR', value=s)
    sleeves = ['SLEEVELESS', 'HALF SLEEVES', '3/4 SLEEVES', 'FULL SLEEVES']
    for s in sleeves:
        CategoryVarient.objects.create(
            category=category, varient_type='SLEEVES', value=s)
    neck = ['ROUND NECK', 'V NECK']
    for s in neck:
        CategoryVarient.objects.create(
            category=category, varient_type='NECK', value=s)
    fitting = ['REGULAR FIT', 'SLIM FIT', 'LOOSE FIT']
    for s in fitting:
        CategoryVarient.objects.create(
            category=category, varient_type='FITTING', value=s)
    fabric = ['COTTON', 'COTTON LYCRA']
    for s in size:
        CategoryVarient.objects.create(
            category=category, varient_type='FABRIC', value=s)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productvarientlist_product_image'),
    ]

    operations = [
        migrations.RunPython(category_creator),
    ]
