# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-30 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20180104_2152'),
    ]

    def create_category_varient_name(apps, schema_editor):
        CategoryVarient = apps.get_model('product', 'CategoryVarient')
        all_obj = CategoryVarient.objects.all()
        for obj in all_obj:
            obj.name = obj.value
            obj.save()

    operations = [
        migrations.AddField(
            model_name='categoryvarient',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(create_category_varient_name)
    ]
