# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-25 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20180104_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproducts',
            name='combo_type',
            field=models.CharField(blank=True, choices=[('COUPLE', 'COUPLE')], max_length=150),
        ),
    ]
