# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-31 23:42
from __future__ import unicode_literals

from django.db import migrations
from product.models import Category, ProductVarientList, CategoryVarient


class Migration(migrations.Migration):

    def create_new_category_varient_tshirt(apps, schema_editor):
        category_obj = Category.objects.get(name='tshirt')
        cv_obj = CategoryVarient.objects.create(category=category_obj, varient_type='TYPE', value='PRINTED', name='PRINTED')
        pv_obj = ProductVarientList.objects.filter(product__category__name='tshirt')
        for obj in pv_obj:
            obj.key.add(cv_obj)

    dependencies = [
        ('product', '0035_categoryvarient_name'),
    ]

    operations = [
        migrations.RunPython(create_new_category_varient_tshirt)
    ]
