# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-01 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20180201_0512'),
        ('product', '0035_comboproducts_combo_type'),
    ]

    operations = [
    ]
