# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_auto_20180722_2107'),
        ('product', '0037_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.ArtistDetail'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
