# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-30 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20180722_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='rule',
            field=models.CharField(max_length=200),
        ),
    ]
