# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-29 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_shippingcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
