# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-01 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20170430_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pickup_pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
