# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20170502_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellervatdetails',
            name='cst_no',
        ),
        migrations.RemoveField(
            model_name='sellervatdetails',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='sellervatdetails',
            name='legal_city',
        ),
        migrations.RemoveField(
            model_name='sellervatdetails',
            name='legal_pin_code',
        ),
        migrations.RemoveField(
            model_name='sellervatdetails',
            name='legal_state',
        ),
        migrations.RemoveField(
            model_name='sellervatdetails',
            name='tin_no',
        ),
        migrations.AddField(
            model_name='seller',
            name='average_dispatch_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='display_name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='pickup_country',
            field=models.CharField(default=b'India', max_length=60),
        ),
        migrations.AddField(
            model_name='seller',
            name='shop_country',
            field=models.CharField(default=b'India', max_length=60),
        ),
        migrations.AddField(
            model_name='sellerbankdetails',
            name='cheque',
            field=models.FileField(blank=True, upload_to=seller.models.get_file_path),
        ),
        migrations.AddField(
            model_name='sellervatdetails',
            name='cin_memo',
            field=models.FileField(blank=True, upload_to=seller.models.get_file_path),
        ),
        migrations.AddField(
            model_name='sellervatdetails',
            name='cin_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellervatdetails',
            name='gst_certificate',
            field=models.FileField(blank=True, upload_to=seller.models.get_file_path),
        ),
        migrations.AddField(
            model_name='sellervatdetails',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sellervatdetails',
            name='sign',
            field=models.FileField(blank=True, upload_to=seller.models.get_file_path),
        ),
    ]
