# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-04 19:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mta', models.CharField(choices=[('SENDGRID', 'sendgrid')], default=b'sendgrid', max_length=100)),
                ('sta', models.CharField(choices=[('MSG91', 'msg91')], default=b'msg91', max_length=100)),
                ('nid', models.CharField(max_length=150)),
                ('about', models.TextField()),
                ('is_email', models.BooleanField(default=False)),
                ('is_sms', models.BooleanField(default=False)),
                ('email_template', models.TextField(blank=True, null=True)),
                ('sms_template', models.CharField(blank=True, max_length=500, null=True)),
                ('auto_send', models.BooleanField(default=False)),
                ('email_to', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=[], help_text="The default receivers of email. Enter email address separated by ','", null=True, size=None)),
                ('email_bcc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=[], help_text="Email bcc. Enter email address separated by ','", null=True, size=None)),
                ('subject_content', models.TextField(blank=True, help_text='Email subject content')),
                ('sms_content', models.TextField(blank=True)),
                ('numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, default=[], help_text="The default receivers of sms. Enter numbers separated by ','", null=True, size=None)),
                ('sender_name', models.CharField(default=b'Addiction Bazaar', max_length=100)),
                ('sender_email', models.CharField(default=b'noreply@addictionbazaar.com', max_length=100)),
            ],
        ),
    ]
