module.exports = {
    LOAD_IMG_SLIDER: 'LOAD_IMG_SLIDER',
    RECEIVE_IMAGES: 'RECEIVE_IMAGES',

    RECEIVE_USER_DETAILS: 'RECEIVE_USER_DETAILS',
    RECIEVE_IS_USER_AUTHENTICATED: 'RECIEVE_IS_USER_AUTHENTICATED',
    RECEIVE_ORDER_USER_DETAILS: 'RECEIVE_ORDER_USER_DETAILS',
    UPDATE_EMAIL_SENT_STATUS: 'UPDATE_EMAIL_SENT_STATUS',
    UPDATE_CART: 'UPDATE_CART',
    SIGNIN_STATUS: 'SIGNIN_STATUS',
    RECEIVE_USER_WALLET: 'RECEIVE_USER_WALLET',
    RECEIVE_REDEEM_VALUE: 'RECEIVE_REDEEM_VALUE',


    // Designer constant
    RECEIVE_DESIGNER_DETAILS: 'RECEIVE_DESIGNER_DETAILS',
    // product
    RECEIVE_PRODUCT_DETAILS: 'RECEIVE_PRODUCT_DETAILS',
    RECEIVE_ALL_PRODUCTS: 'RECEIVE_ALL_PRODUCTS',
    
    // Pincode status
    RECEIVE_PINCODE_STATUS: 'RECEIVE_PINCODE_STATUS',

    RECEIVE_ALL_PRODUCT_VARIENTS: 'RECEIVE_ALL_PRODUCT_VARIENTS',

    RECEIVE_PRODUCT_PRICE_AND_VARIENTS: 'RECEIVE_PRODUCT_PRICE_AND_VARIENTS',
    // auraai constant
    RECEIVE_TAG_SEARCH_PRODUCTS: 'RECEIVE_TAG_SEARCH_PRODUCTS',
    RECEIVE_ALL_BANNERS: 'RECEIVE_ALL_BANNERS',
    AUTOCOMPLETE_KEYS: 'AUTOCOMPLETE_KEYS',
    // artist details
    RECEIVE_ARTIST_DETAILS: 'RECEIVE_ARTIST_DETAILS',
    // artsit designs
    RECEIVE_ARTIST_DESIGNS: 'RECEIVE_ARTIST_DESIGNS',
    // artist Social Links
    RECEIVE_ARTIST_SOCIAL_LINKS: 'RECEIVE_ARTIST_SOCIAL_LINKS',
    // artist Other Details
    RECEIVE_ARTIST_OTHER_DETAILS: 'RECEIVE_ARTIST_OTHER_DETAILS',
    // artist Bank Details
    RECEIVE_ARTIST_BANK_DETAILS: 'RECEIVE_ARTIST_BANK_DETAILS',
}