# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfibaaz',
            old_name='product_photo',
            new_name='selfi',
        ),
        migrations.AddField(
            model_name='selfibaaz',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
