# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import myhome.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160731_1228'),
        ('myhome', '0002_auto_20160724_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_on_page', models.ImageField(blank=True, default=b'uploads/blogimages/dummy.jpg', null=True, upload_to=myhome.models.home_page_image_upload)),
                ('image_on_menu', models.ImageField(blank=True, default=b'uploads/blogimages/dummy.jpg', null=True, upload_to=myhome.models.home_page_image_upload)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OtherBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, default=b'uploads/blogimages/dummy.jpg', null=True, upload_to=myhome.models.home_page_image_upload)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, default=b'uploads/blogimages/dummy.jpg', null=True, upload_to=myhome.models.home_page_image_upload)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
