# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0005_customer_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimages',
            name='display_priority',
            field=models.IntegerField(null=True),
        ),
    ]
