# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0006_sliderimages_display_priority'),
    ]

    database_operations = [
        migrations.AlterModelTable('Customer', 'customer_customer'),
        migrations.AlterModelTable('CustomerAddress', 'customerAddress_customerAddress')
    ]

    state_operations = [
        migrations.DeleteModel('Customer'),
        migrations.DeleteModel('CustomerAddress')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
