# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import myhome.models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0007_auto_20170128_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimages',
            name='image_mobile',
            field=models.ImageField(blank=True, default=b'uploads/blogimages/dummy.jpg', null=True, upload_to=myhome.models.home_page_image_upload_mobile),
        ),
        migrations.AddField(
            model_name='sliderimages',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
