# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-29 21:36
from __future__ import unicode_literals

import designer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0003_auto_20170430_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('awards', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('working_since', models.DateTimeField(blank=True, null=True)),
                ('about', models.CharField(blank=True, max_length=2000, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('user_photo', models.ImageField(blank=True, default='uploads/user_dummy.jpg', null=True, upload_to=designer.models.get_user_image_path)),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ab_designer', to='seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='DesignerSocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('fb', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ab_designer_social_links', to='designer.Designer')),
            ],
        ),
    ]
