# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-01 21:08
from __future__ import unicode_literals

import designer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerSliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, default='uploads/blogimages/dummy.jpg', null=True, upload_to=designer.models.designer_slider_images)),
                ('active', models.BooleanField(default=False)),
                ('display_priority', models.IntegerField(null=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Designer')),
            ],
        ),
    ]
