# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-29 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_designercollageimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=60)),
                ('website', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('DRAFT', 'draft'), ('CONTACTED', 'contacted'), ('RESPONDED', 'responded'), ('FOLLOWUP', 'followup'), ('ONBOARDED', 'onboarded')], max_length=60)),
                ('contact_channel', models.CharField(choices=[('EMAIL', 'email'), ('INPERSON', 'inperson'), ('SELF', 'self')], max_length=60)),
                ('remarks', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
