# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-01 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_designercontactdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='designercontactdetails',
            name='unique_id',
            field=django_extensions.db.fields.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='designercontactdetails',
            name='contact_channel',
            field=models.CharField(choices=[('EMAIL', 'email'), ('INPERSON', 'inperson'), ('SELF', 'self')], default=('INPERSON', 'inperson'), max_length=60),
        ),
        migrations.AlterField(
            model_name='designercontactdetails',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('CONTACTED', 'contacted'), ('RESPONDED', 'responded'), ('FOLLOWUP', 'followup'), ('ONBOARDED', 'onboarded'), ('REFUSED', 'refused')], default=('CONTACTED', 'contacted'), max_length=60),
        ),
    ]
