# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-27 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expencedetails',
            name='expense_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
