# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_auto_20170729_2121'),
        ('seller', '0005_auto_20170729_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('aipex_number', models.CharField(blank=True, max_length=100)),
                ('api_id', models.CharField(blank=True, max_length=100)),
                ('ship_label', models.CharField(blank=True, max_length=100)),
                ('cod_label', models.CharField(blank=True, max_length=100)),
                ('way_bill_no', models.CharField(blank=True, max_length=100)),
                ('request_json', models.TextField()),
                ('response_json', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartnerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('delivery_available', models.BooleanField(default=True)),
                ('pickup_available', models.BooleanField(default=True)),
                ('cod_available', models.BooleanField(default=True)),
                ('prepaid_available', models.BooleanField(default=True)),
                ('cod_charge', models.IntegerField(blank=True, null=True)),
                ('surface_charge', models.IntegerField(blank=True, null=True)),
                ('air_charge', models.IntegerField(blank=True, null=True)),
                ('cargo_available', models.BooleanField(default=True)),
                ('cargo_charge', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SellerPickupAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psi', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('request_data', models.TextField()),
                ('response_json', models.CharField(blank=True, max_length=500)),
                ('delivery_partner', models.CharField(blank=True, max_length=500)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='deliverypartnerdetails',
            name='pincode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absupport.Pincode'),
        ),
        migrations.AddField(
            model_name='deliveryorders',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absupport.SellerPickupAddress'),
        ),
    ]
