# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absupport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpickupaddress',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
    ]
