# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-06 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absupport', '0002_auto_20170802_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
