# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absupport', '0003_auto_20170807_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='pincode',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
