# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-25 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absupport', '0004_auto_20170811_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorders',
            name='cod_label',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deliveryorders',
            name='ship_label',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deliveryorders',
            name='way_bill_no',
            field=models.TextField(blank=True),
        ),
    ]
