# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absupport', '0005_auto_20170826_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCacheForSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=275)),
                ('file_name', models.CharField(max_length=275)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
