# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absupport', '0006_pagecacheforseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecacheforseo',
            name='file_name_mobile',
            field=models.CharField(blank=True, default='home.html', max_length=275, null=True),
        ),
    ]
