# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-09 18:25
from __future__ import unicode_literals

import artist.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0021_auto_20170909_2355'),
        ('customer', '0008_remove_customer_is_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=60)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=15)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('account_no', models.CharField(max_length=30)),
                ('bank_branch_address', models.CharField(max_length=200)),
                ('account_type', models.CharField(blank=True, choices=[('SAVING', 'SAVING'), ('CURRENT', 'CURRENT')], max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, max_length=1500, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], max_length=150)),
                ('design', models.FileField(blank=True, default='uploads/blogimages/dummy.jpg', null=True, upload_to=artist.models.get_artwork_path)),
                ('categoty', models.ManyToManyField(to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_code', models.IntegerField(null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('artist_type', models.CharField(blank=True, choices=[('INDEPENDENT', 'INDEPENDENT'), ('YOUTUBER', 'YOUTUBER'), ('BLOGGER', 'BLOGGER'), ('NGO', 'NGO')], max_length=60, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600)),
                ('website', models.CharField(blank=True, choices=[('FACEBOOK', 'FACEBOOK'), ('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER'), ('YOUTUBE', 'YOUTUBE'), ('GOOGLE_PLUS', 'GOOGLE_PLUS'), ('TUMBLER', 'TUMBLER'), ('PINTREST', 'PINTREST'), ('BEHANCE', 'BEHANCE'), ('OTHER', 'OTHER')], max_length=60, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.ArtistDetail')),
            ],
        ),
        migrations.AddField(
            model_name='artistdesign',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_artist', to='artist.ArtistDetail'),
        ),
        migrations.AddField(
            model_name='artistbankdetail',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.ArtistDetail'),
        ),
    ]
