# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-12 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20170909_2355'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArtistDesignMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.ArtistDesign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
