# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_productartistdesignmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdesign',
            name='tags',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
