# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artistdesign_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
