# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-07 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20170923_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='productartistdesignmap',
            name='product_type',
            field=models.CharField(choices=[(b'mens-half-sleeves-round-neck-tshirt', b'mens-half-sleeves-round-neck-tshirt'), (b'mens-vest', b'mens-vest'), (b'mens-plain-tshirt', b'mens-plain-tshirt'), (b'mens-polo-tshirt', b'mens-polo-tshirt'), (b'mens-full-sleeves-round-neck-tshirt', b'mens-full-sleeves-round-neck-tshirt'), (b'womens-plain-tshirt', b'womens-plain-tshirt'), (b'womens-half-sleeves-round-neck-tshirt', b'womens-half-sleeves-round-neck-tshirt'), (b'croptop', b'croptop'), (b'womens-polo-tshirt', b'womens-polo-tshirt'), (b'womens-full-sleeves-round-neck-tshirt', b'womens-full-sleeves-round-neck-tshirt')], default='mens-half-sleeves-round-neck-tshirt', max_length=150),
            preserve_default=False,
        ),
    ]
