# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20180116_0801'),
        ('artist', '0007_auto_20180722_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistCoupon',
            fields=[
                ('coupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.Coupon')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.ArtistDetail')),
            ],
            bases=('customer.coupon',),
        ),
    ]
