# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_transaction_id', models.BigIntegerField(db_index=True)),
                ('_transaction_app_label', models.CharField(max_length=250)),
                ('_transaction_model_name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=20, verbose_name='status')),
                ('raw', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='raw')),
                ('reference_id', models.CharField(blank=True, max_length=250)),
                ('payment_id', django_extensions.db.fields.UUIDField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='data')),
                ('type', models.CharField(choices=[('BROWSER', 'Broswer'), ('S2SQUERY', 'S2SQuery')], default='BROWSER', max_length=20, verbose_name='request type')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='data')),
                ('type', models.CharField(choices=[('BROWSER', 'Broswer'), ('S2S', 'S2S'), ('S2SQUERY', 'S2SQuery')], default='BROWSER', max_length=20, verbose_name='response type')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.Payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.PaymentGateway'),
        ),
    ]
