"""
Django settings for codeab project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2hpwb7prd_#!_9i-9=e_x3n7uv8x)6i@7bjk!6-o1+v!_9!_o!'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False
ALLOWED_HOSTS = ['addictionbazaar.com', 'seller.addictionbazaar.com',
                 'www.addictionbazaar.com', '139.162.212.88', 'test.addictionbazaar.com',
                 'dashboard.addictionbazaar.com']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'django.contrib.postgres',
    'django.contrib.sitemaps',
    'webpack_loader',
    'corsheaders',
    'rest_framework',
    'myhome',
    'seller',
    'blog',
    'product',
    'orders',
    'notification',
    'payment_gateway',
    'designer',
    'social.apps.django_app.default',
    'absupport',
    'raven.contrib.django.raven_compat',
    'customer',
    'multiselectfield',
    'master_password',
    'expense',
    'auraai',
    'artist',
    'tagging',
    'cfblog',
    'vyomab',
)

MIDDLEWARE_CLASSES = (
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'subdomains.middleware.SubdomainURLRoutingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'myhome.update_cart_middleware.UpdateCartMiddleware',
    'myhome.Middleware.Middleware',
    'cfblog.Middleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'vyomab.middleware.VisitorTrackingMiddleware',
)

ROOT_URLCONF = 'codeab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'templates', 'blog'),
                 os.path.join(BASE_DIR, 'templates', 'seller'),
                 os.path.join(BASE_DIR, 'templates', 'product'),
                 os.path.join(BASE_DIR, 'templates', 'grocery'),
                 os.path.join(BASE_DIR, 'templates', 'absupport'),
                 os.path.join(BASE_DIR, 'templates', 'expense'),
                 os.path.join(BASE_DIR, 'templates', 'cached'),
                 os.path.join(BASE_DIR, 'templates', 'user')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
                'django.core.context_processors.static',
                'django.core.context_processors.tz',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
                'myhome.context_processors.static_file_version'
            ],
        },
    },
]

WSGI_APPLICATION = 'codeab.wsgi.application'


AUTHENTICATION_BACKENDS = (
    'social.backends.facebook.FacebookOAuth2',
    'social.backends.google.GoogleOAuth2',
    'social.backends.twitter.TwitterOAuth',
    'django.contrib.auth.backends.ModelBackend',
    'master_password.auth.ModelBackend',
)


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'abdb',
        'USER': 'postgres',                      # Not used with sqlite3.
        'PASSWORD': 'mishraAcodeab',                  # Not used with sqlite3.
        'HOST': 'codeab.cup4aktoih8z.eu-west-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}


PAYU_INFO = {
    'merchant_key': "Obf62W",
    'merchant_salt': "YQ7GBS3Z",

    # for production environment use 'https://secure.payu.in/_payment'
    'payment_url': 'https://secure.payu.in/_payment',
    'surl': 'https://www.addictionbazaar.com/pay-success/',
    'furl': 'https://www.addictionbazaar.com/failure/',
    'curl': 'https://www.addictionbazaar.com/cancel/',

    # testing
    # 'merchant_key': "gtKFFx",
    # 'merchant_salt': "eCwWELxi",
    # 'payment_url': 'https://test.payu.in/_payment',
    # 'surl':'http://test.com:8000/pay-success/',
    # 'furl':'http://test.com:8000/failure/',
    # 'curl':'http://test.com:8000/cancel/',
}
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Calcutta'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 3

SUBDOMAIN_URLCONFS = {
    None: 'codeab.urls',
    'test': 'codeab.urls',
    'm': 'underc.urls',
    'www': 'codeab.urls',
    'seller': 'seller.urls',
    'dashboard': 'absupport.apis.urls',
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

LOGIN_REDIRECT_URL = '/'

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static_content/'),
    os.path.join(BASE_DIR, '..', '..', 'ab-frontend', 'media/'),
    os.path.join(BASE_DIR, '..', '..', 'ab-frontend', 'public/'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# ADMIN_MEDIA_PREFIX = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/uploads/'

SOCIAL_AUTH_FACEBOOK_KEY = '1787057741532094'
SOCIAL_AUTH_FACEBOOK_SECRET = '3412e897286867bd9818efd8336f4c05'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email',
}
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '561286558492-9ggu885ign1qj2eqerclamlj416frp02.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'DTR13DWmVm6ln2Vtd-Yz1ZA4'
GOOGLE_SHORT_URL_KEY = 'AIzaSyBYA4sD1BO-yetLIi262yZNp0cOvbomudk'

DEFAULT_MTA = "sendgrid"
DEFAULT_STA = "msg91"

DEFAULT_FROM_NAME = "Addiction Bazaar"
DEFAULT_FROM_EMAIL = "noreply@addictionbazaar.com"
MSG91_KEY = '124493ANcPRtUzyOos584cfdf9'

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
RAVEN_CONFIG = {
    'dsn': 'https://c12ebaf545af45a69b4879bfe08bbf55:dd82213a06504d7fbfa1c30b9af04367@sentry.io/127925',
    # If you are using git, you can also automatically configure the
    # release based on the git info.
}

MASTER_PASSWORDS = {
    'pbkdf2_sha256$24000$WIAh9m8BGoF8$Wu4BB03jgP7r2488SBAWnh5kqoQBvrv7SZ7Vn5TbfmY=': None,
}

MAINTAINANCE = False
PRODUCTS_FROM_CACHE = True
REDIS_CLIENT = "default"

APEX_SANDBOX_URL = "http://aipexworldwide.com/sandbox/index.php"
APEX_PRODUCTION_URL = "http://aipexworldwide.com/shiplive/index.php"
APEX_USERNAME = 'addictionbazaar@gmail.com'
APEX_PASSWORD = 'ncdg9582'
APEX_TOKEN = '012335A9CC'


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CACHE_TTL = 60 * 15


PAYTM_MERCHANT_KEY = 'iiKshw&amRYC39GE'
PAYTM_MERCHANT_ID = 'VhaBaz44512566558685'
PAYTM_CALLBACK_URL = 'https://www.addictionbazaar.com/paytm/response/'
LOG_DIR = '/home/ubuntu/codeab/logs/ab.log'

TRACK_ENABLE = False
TRACK_PAGEVIEWS = True

WEBPACK_LOADER = {
    'DEFAULT': {
        # 'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': '/static/', # must end with slash
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'TIMEOUT': None,
        # 'IGNORE': ['.+\.hot-update.js', '.+\.map']
    }
}

CORS_ORIGIN_ALLOW_ALL = True

try:
    from local_settings import *
except:
    pass
