# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_auto_20160806_1811'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed_time', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('shipping_address', models.CharField(blank=True, max_length=250)),
                ('order_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAYMENT_DONE', 'PAYMENT_DONE'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('RETURNED', 'RETURNED'), ('CANCELLED', 'CANCELLED')], max_length=50)),
                ('track_code', models.CharField(blank=True, max_length=250)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('shipping_charge', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_token', models.CharField(blank=True, max_length=250)),
                ('payment_id', django_extensions.db.fields.UUIDField(blank=True, editable=False, unique=True)),
                ('payment_on', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.IntegerField()),
                ('payment_mode', models.CharField(blank=True, max_length=250)),
                ('payment_status', models.CharField(blank=True, max_length=250)),
                ('coupon_applied', models.CharField(blank=True, max_length=250)),
                ('discount', models.IntegerField()),
                ('taxes', models.IntegerField()),
                ('order', models.ManyToManyField(to='orders.Order')),
            ],
        ),
    ]
