# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_firstname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_lastname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zipcode',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('PAYMENT_DONE', 'PAYMENT_DONE'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('RETURNED', 'RETURNED'), ('CANCELLED', 'CANCELLED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(default=0),
        ),
    ]
