# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160806_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
