# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20160811_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_other_detail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
