# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-26 22:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_other_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_request',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_response',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=None, null=True),
        ),
    ]
