# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-15 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from product.models import ProductVarientList


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0023_auto_20170916_0138'),
        ('seller', '0005_auto_20170729_2121'),
        ('orders', '0010_auto_20170826_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='process_by_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_varient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.ProductVarientList'),
        ),
    ]
