# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-23 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20170916_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_varient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductVarientList'),
        ),
    ]
