# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-23 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20171011_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_other_detail',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('COD', 'COD'), ('PAYTM', 'PAYTM')], max_length=50),
        ),
    ]
