# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20171024_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='coupon_applied',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
