# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-02 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20171102_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_from_abmoney',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
