# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-04 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_transaction_payment_from_abmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
    ]
