# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-18 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20171104_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('DROP', 'DROP'), ('FAILED', 'FAILED'), ('TAMPERED', 'TAMPERED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], max_length=250),
        ),
    ]
