# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-01 14:58
from __future__ import unicode_literals

import auraai.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('imported_from', models.CharField(blank=True, max_length=200)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('image_for', models.CharField(blank=True, choices=[('TOP', 'top'), ('BOTTOM', 'bottom'), ('WHOLE', 'whole')], default=('WHOLE', 'whole'), max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('likes_top', models.IntegerField(default=0)),
                ('likes_bottom', models.IntegerField(default=0)),
                ('likes_whole', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('riplicable', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=auraai.models.get_file_path)),
                ('relevent', models.BooleanField(default=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhysique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('body_type', models.CharField(blank=True, choices=[('AVERAGE', 'average'), ('EXTRA', 'extra'), ('ATHLETIC', 'athletic'), ('SLIM', 'slim'), ('BIG&BOLD', 'big&bold'), ('MUSCULAR', 'muscular')], default=('AVERAGE', 'average'), max_length=60)),
                ('hair_color', models.CharField(blank=True, choices=[('BLACK', 'black'), ('BROWN', 'brown'), ('GREEN', 'green'), ('BLUE', 'BLUE'), ('GREY', 'grey'), ('HAZEL', 'hazel')], default=('BLACK', 'black'), max_length=60)),
                ('eye_color', models.CharField(blank=True, choices=[('BLACK', 'black'), ('BROWN', 'brown'), ('RED', 'red'), ('BLOND', 'blond'), ('GREY', 'grey'), ('WHITE', 'white'), ('SHAVED', 'shaved'), ('DYED', 'dyed'), ('BULD', 'buld')], default=('BLACK', 'black'), max_length=60)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], default=('MALE', 'male'), max_length=20)),
                ('age', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
