# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-08 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auraai', '0002_user_fb_details_user_fb_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_fb_details',
            new_name='UserFbDetails',
        ),
        migrations.RenameModel(
            old_name='user_fb_likes',
            new_name='UserFbLikes',
        ),
    ]
