# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-26 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auraai', '0006_tagbanner_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagbanner',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
